# Use postgres/example user/password credentials
services:

  db:
    container_name: "app_db"
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
       - 5432:5432
    env_file:
        - ./.env
    volumes:
       - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=go_rssagg,node_rssagg
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}


